import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

export const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SHELL_BUDGET_BYTES = 6_000_000;
export const OPTIONAL_ART_CACHE = 'dbz-v7-art-v1';
export const VISITED_ART_CACHE = 'dbz-v7-art-visited-v2';

export function walkFiles(directory, prefix = '') {
    return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
        const name = prefix ? `${prefix}/${entry.name}` : entry.name;
        if (entry.name.startsWith('.') || entry.name === 'node_modules') return [];
        if (entry.isDirectory()) return walkFiles(path.join(directory, entry.name), name);
        return entry.isFile() ? [name] : [];
    }).sort();
}

/** Pure manifest inspection: importing this module never builds or rewrites the release. */
export function buildManifest(root = PROJECT_ROOT) {
    const runtimeModules = walkFiles(path.join(root, 'v7'), 'v7').filter(file => /\.(?:js|css)$/.test(file));
    const bootstrapArt = walkFiles(path.join(root, 'images/v7'), 'images/v7').filter(file => /\/(?:mountain-dawn|turtle-sanctuary|awakening|portrait-[a-z_]+)(?:-mobile)?\.webp$/.test(file));
    const legacyPortraits = fs.existsSync(path.join(root, 'images/race_portraits')) ? walkFiles(path.join(root, 'images/race_portraits'), 'images/race_portraits').filter(file => file.endsWith('.webp')) : [];
    const precache = [...new Set(['./', 'index.html', 'DragonBall_Fitness_RPG_v7.0.html', 'DragonBall_Fitness_RPG_v6.0.html', 'manifest-v7.webmanifest', 'manifest-v6.webmanifest', 'manifest.webmanifest', ...runtimeModules,
        'icons/icon-192.png', 'icons/icon-512.png', 'icons/apple-touch-icon.png', 'images/v6/v6_hero.webp',
        ...bootstrapArt, ...legacyPortraits, 'images/partners/bulma.webp', 'images/partners/kid_goku.webp', 'images/partners/master_roshi.webp'])];
    for (const file of precache.filter(file => file !== './')) if (!fs.existsSync(path.join(root, file))) throw Error(`Missing install resource: ${file}`);
    const digest = crypto.createHash('sha256');
    for (const file of precache.filter(file => file !== './')) digest.update(file).update(fs.readFileSync(path.join(root, file)));
    const art = walkFiles(path.join(root, 'images/v7'), 'images/v7').filter(file => file.endsWith('.webp'));
    const precacheBytes = precache.filter(file => file !== './').reduce((total, file) => total + fs.statSync(path.join(root, file)).size, 0);
    return { version: '7.0.0', build: `7.0.0-${digest.digest('hex').slice(0, 12)}`, entry: 'DragonBall_Fitness_RPG_v7.0.html', schemaVersion: 70,
        precache, precacheBytes, shellBudgetBytes: SHELL_BUDGET_BYTES, runtimeModules,
        optionalArt: art.filter(file => !precache.includes(file)), optionalArtCache: OPTIONAL_ART_CACHE,
        visitedArtCache: VISITED_ART_CACHE, notes: 'Immutable prior reward rules are precached. Individual equipment, transformation and technique art ships in the package and is available through the optional full-art download.' };
}

export function serviceWorkerSource(report) {
    return `// Generated by analysis/build_v7_release.mjs.
const BUILD=${JSON.stringify(report.build)};
const SHELL='dbz-v7-shell-'+BUILD;
const ART=${JSON.stringify(OPTIONAL_ART_CACHE)};
const VISITED=${JSON.stringify(VISITED_ART_CACHE)};
const PRECACHE=${JSON.stringify(report.precache)};
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(SHELL);await cache.addAll(PRECACHE);await self.skipWaiting();})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const name of await caches.keys())if(name.startsWith('dbz-v7-shell-')&&name!==SHELL)await caches.delete(name);await self.clients.claim();})()));
const canonical=request=>{const url=new URL(request.url);url.search='';return url.href;};
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);
 if(request.method!=='GET'||url.origin!==self.location.origin)return;
 if(request.mode==='navigate') {event.respondWith((async()=>{try{const response=await fetch(request);if(response.ok){const cache=await caches.open(SHELL);await cache.put(request,response.clone());}return response;}catch{const cache=await caches.open(SHELL);return await cache.match(request)||await cache.match('DragonBall_Fitness_RPG_v7.0.html')||Response.error();}})());return;}
 if(/\\.(?:webp|png|jpe?g|svg)$/i.test(url.pathname)) {
   event.respondWith((async()=>{
     const key=canonical(request),pack=await caches.open(ART),visited=await caches.open(VISITED),shell=await caches.open(SHELL);
     const saved=await pack.match(key),hit=saved||await visited.match(key)||await shell.match(key);
     const fresh=fetch(request).then(async response=>{if(response.ok){const destination=saved?pack:visited;await destination.put(key,response.clone());if(!saved){const keys=await visited.keys();if(keys.length>96)await visited.delete(keys[0]);}}return response;}).catch(()=>hit||Response.error());
     event.waitUntil(fresh.then(()=>{}));return request.cache==='reload'?await fresh:hit||await fresh;
   })());return;
 }
 event.respondWith((async()=>{const cache=await caches.open(SHELL);const hit=await cache.match(canonical(request));if(hit)return hit;try{const response=await fetch(request);if(response.ok)await cache.put(canonical(request),response.clone());return response;}catch{return Response.error();}})());
});
`;
}

export function buildRelease(root = PROJECT_ROOT) {
    fs.copyFileSync(path.join(root, 'DragonBall_Fitness_RPG_v7.0.html'), path.join(root, 'index.html'));
    // Preserve installed v6 launch URLs on the same origin and storage scope.
    fs.copyFileSync(path.join(root, 'DragonBall_Fitness_RPG_v7.0.html'), path.join(root, 'DragonBall_Fitness_RPG_v6.0.html'));
    // GitHub serves LF text. Normalize before hashing so Windows builds describe
    // the exact published bytes, not a checkout-specific newline conversion.
    for (const file of buildManifest(root).precache.filter(file => /\.(?:js|css|html|webmanifest)$/.test(file))) {
        const target = path.join(root, file), source = fs.readFileSync(target, 'utf8');
        if (source.includes('\r\n')) fs.writeFileSync(target, source.replace(/\r\n/g, '\n'));
    }
    const report = buildManifest(root);
    if (report.precacheBytes > SHELL_BUDGET_BYTES) throw Error(`Install shell is ${report.precacheBytes.toLocaleString()} bytes, above the ${SHELL_BUDGET_BYTES.toLocaleString()} byte budget. Keep collection artwork optional.`);
    fs.writeFileSync(path.join(root, 'dbz-sw-v7.js'), serviceWorkerSource(report));
    for (const name of ['dbz-sw-v6.0.js', 'dbz-sw-v5.0.js']) {
        fs.writeFileSync(path.join(root, name), `// Upgrade existing installed apps to the current v7 worker.\nimportScripts('./dbz-sw-v7.js?build=${report.build}');\n`);
    }
    fs.writeFileSync(path.join(root, 'v7/release.json'), JSON.stringify(report, null, 2) + '\n');
    return report;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const report = buildRelease();
    console.log(JSON.stringify({ build: report.build, files: report.precache.length, bytes: report.precacheBytes, optionalArt: report.optionalArt.length }));
}
